#!/usr/bin/env python
# Tiny helper script to make adding dependencies to the project a little 
# simpler.
import argparse
import os

parser = argparse.ArgumentParser(
    prog="Install",
    description="Add a dependency to our project.",
)
parser.add_argument("dependency")
parser.add_argument("-D", "--development", action="store_true")
args = parser.parse_args()

the_file = "./requirements-dev.in" if args.development else "./requirements.in"
with open(the_file, "a+") as needs_appending:
    needs_appending.write(f"{args.dependency}\n")

if args.development:
    os.system("pip-compile requirements-dev.in -o requirements-dev.txt")
else:
    os.system("pip-compile")

os.system("pip install -r requirements-dev.txt")
os.system("cp requirements.txt ..")
